title: Asleep84
description:  Chord Charts for Worship Songs Using the Nashville Number System
remote_theme: tuur29/pages-themes-cayman
darkmode: true
color:
  header: "#fff"
  gradient_left: "#00FFFF"
  gradient_right: "#FF369b"
logo_url: 
gems:
- jekyll-seo-tag
