title: Asleep84
description:  nothing here works except en music, victory, planetshakers, hillsong, and midcities!1!
remote_theme: tuur29/pages-themes-cayman
darkmode: true
color:
  header: "#fff"
  gradient_left: "#00FFFF"
  gradient_right: "#FF369b"
logo_url: 
gems:
- jekyll-seo-tag
